### ISSUE TITLE
sql数据缺失？

### ISSUE THREAD

**Issue by HHC26** [iimeta/fastapi-admin#1]
没看到有sql数据

**Comment by iimeta** [comment]
目前现在还在开发中, 还没开发好, 不过用的数据库是MongoDB, 基本上程序跑起来就能正常使用了, 不需要导入sql

**Comment by iimeta** [comment]
> 没看到有sql数据


目前现在还在开发中, 还没开发好, 不过用的数据库是MongoDB, 基本上程序跑起来就能正常使用了, 不需要导入sql
