### ISSUE TITLE
panic：implement not found for interface isession forget register?

### ISSUE THREAD

**Issue by mobeixiaoxin** [iimeta/fastapi-admin#2]
运行程序，链接mongodb和redis数据库正常，fastapi库的表也能正常创建出来，报错panic：implement not found for interface isession forget register? 请问大佬知道是什么原因引起的么？

**Comment by mobeixiaoxin** [comment]
使用的go 1.20版本，仅将go 1.22支持的slice包替换，其余未做改动

**Comment by iimeta** [comment]
> 使用的go 1.20版本，仅将go 1.22支持的slice包替换，其余未做改动

用最新的gf和go版本试试
