### ISSUE TITLE
无法启动容器

### ISSUE THREAD

**Issue by fgjfjfjfteyerifhfj** [iimeta/fastapi-admin#3]
在运行docker run --name fastapi-admin -d -p 8080:8080 \
  --network host \
  --restart=always \
  -v /etc/localtime:/etc/localtime:ro \
  -v /data/fastapi-admin/manifest/config/config.yaml:/app/manifest/config/config.yaml \
  -v /data/fastapi-admin/resource/public:/app/resource/public \
  registry.cn-hangzhou.aliyuncs.com/iimeta/fastapi-admin:latest 后出现WARNING: Published ports are discarded when using host network mode 然后容器也没有启动，请问大佬这是什么原因呢？

**Comment by iimeta** [comment]
> 在运行docker run --name fastapi-admin -d -p 8080:8080 --network host --restart=always -v /etc/localtime:/etc/localtime:ro -v /data/fastapi-admin/manifest/config/config.yaml:/app/manifest/config/config.yaml -v /data/fastapi-admin/resource/public:/app/resource/public registry.cn-hangzhou.aliyuncs.com/iimeta/fastapi-admin:latest 后出现WARNING: Published ports are discarded when using host network mode 然后容器也没有启动，请问大佬这是什么原因呢？

警告没关系, 看配置文件/data/fastapi-admin/manifest/config/config.yaml里的Redis和MongoDB参数配置是否正确

**Comment by fgjfjfjfteyerifhfj** [comment]
请问该怎么填呢？
看不懂
![image](https://github.com/user-attachments/assets/d58f3150-2925-4550-bdc1-70ac0d4e825b)
![image](https://github.com/user-attachments/assets/7bcd65ac-7371-4ddc-8af5-295fb95d5680)

**Comment by iimeta** [comment]
> 请问该怎么填呢？
> 看不懂
> ![image](https://github.com/user-attachments/assets/d58f3150-2925-4550-bdc1-70ac0d4e825b)
> ![image](https://github.com/user-attachments/assets/7bcd65ac-7371-4ddc-8af5-295fb95d5680)
> 

建议看一下readme里的部署视频，里面有教怎么配置这些
